<?php
declare(strict_types=1);

final class ModeloCatalogosAdmin
{
    public static function categorias(array $f): array { $db=Conexion::conectar();$w=[];$p=[];if($f['q']!==''){$w[]='(c.nombre LIKE :q_nombre OR c.slug LIKE :q_slug OR c.descripcion LIKE :q_descripcion)';foreach(['q_nombre','q_slug','q_descripcion'] as$k)$p[$k]='%'.$f['q'].'%';}if($f['estado']!==''){$w[]='c.activo=:activo';$p['activo']=(int)$f['estado'];}$s=$db->prepare('SELECT c.idCategoria,c.idCategoriaPadre,c.nombre,c.slug,c.descripcion,c.activo,p.nombre AS padre,(SELECT COUNT(*) FROM afiliados_categorias ac JOIN afiliados a ON a.idAfiliado=ac.idAfiliado WHERE ac.idCategoria=c.idCategoria) afiliados FROM categorias c LEFT JOIN categorias p ON p.idCategoria=c.idCategoriaPadre'.($w?' WHERE '.implode(' AND ',$w):'').' ORDER BY c.activo DESC,COALESCE(p.nombre,\'\'),c.nombre');$s->execute($p);return$s->fetchAll(); }
    public static function resumenCategorias(): array { return Conexion::conectar()->query('SELECT COUNT(*) total,COALESCE(SUM(activo=1),0) activas,COALESCE(SUM(activo=0),0) inactivas,(SELECT COUNT(*) FROM afiliados_categorias) asignaciones FROM categorias')->fetch()?:[]; }
    public static function categoria(int $id): ?array { $s=Conexion::conectar()->prepare('SELECT * FROM categorias WHERE idCategoria=?');$s->execute([$id]);return$s->fetch()?:null; }
    public static function padres(?int $excepto=null): array { $sql='SELECT idCategoria,nombre,idCategoriaPadre FROM categorias WHERE activo=1';$p=[];if($excepto){$sql.=' AND idCategoria<>?';$p[]=$excepto;}$sql.=' ORDER BY nombre';$s=Conexion::conectar()->prepare($sql);$s->execute($p);return$s->fetchAll(); }
    public static function slugExiste(string $slug,?int $excepto): bool { $sql='SELECT 1 FROM categorias WHERE slug=?';$p=[$slug];if($excepto){$sql.=' AND idCategoria<>?';$p[]=$excepto;}$s=Conexion::conectar()->prepare($sql.' LIMIT 1');$s->execute($p);return(bool)$s->fetchColumn(); }
    public static function nombreExiste(string $nombre,?int $padre,?int $excepto): bool { $sql='SELECT 1 FROM categorias WHERE nombre=? AND '.($padre===null?'idCategoriaPadre IS NULL':'idCategoriaPadre=?');$p=[$nombre];if($padre!==null)$p[]=$padre;if($excepto){$sql.=' AND idCategoria<>?';$p[]=$excepto;}$s=Conexion::conectar()->prepare($sql.' LIMIT 1');$s->execute($p);return(bool)$s->fetchColumn(); }
    public static function esDescendiente(int $posiblePadre,int $categoria): bool { $s=Conexion::conectar()->prepare('WITH RECURSIVE descendientes AS (SELECT idCategoria,idCategoriaPadre FROM categorias WHERE idCategoria=? UNION ALL SELECT c.idCategoria,c.idCategoriaPadre FROM categorias c JOIN descendientes d ON c.idCategoriaPadre=d.idCategoria) SELECT 1 FROM descendientes WHERE idCategoria=? LIMIT 1');$s->execute([$categoria,$posiblePadre]);return(bool)$s->fetchColumn(); }
    public static function guardarCategoria(array $d): int { $db=Conexion::conectar();if($d['id']){$s=$db->prepare('UPDATE categorias SET idCategoriaPadre=?,nombre=?,slug=?,descripcion=?,activo=? WHERE idCategoria=?');$s->execute([$d['padre'],$d['nombre'],$d['slug'],$d['descripcion']?:null,$d['activo'],$d['id']]);return$d['id'];}$s=$db->prepare('INSERT INTO categorias(idCategoriaPadre,nombre,slug,descripcion,activo) VALUES(?,?,?,?,?)');$s->execute([$d['padre'],$d['nombre'],$d['slug'],$d['descripcion']?:null,$d['activo']]);return(int)$db->lastInsertId(); }
    public static function estadoCategoria(int $id,bool $activo): bool { $s=Conexion::conectar()->prepare('UPDATE categorias SET activo=? WHERE idCategoria=? AND activo<>?');$s->execute([$activo?1:0,$id,$activo?1:0]);return$s->rowCount()===1; }

    public static function estados(): array { return Conexion::conectar()->query('SELECT e.idEstado,e.clave_inegi,e.nombre,e.activo,(SELECT COUNT(*) FROM municipios m WHERE m.idEstado=e.idEstado) ciudades FROM estados e ORDER BY e.activo DESC,e.nombre')->fetchAll(); }
    public static function ciudades(): array { return Conexion::conectar()->query('SELECT m.idMunicipio,m.idEstado,m.clave_inegi,m.nombre,m.activo,e.nombre AS estado,(SELECT COUNT(*) FROM localidades l WHERE l.idMunicipio=m.idMunicipio) localidades FROM municipios m JOIN estados e ON e.idEstado=m.idEstado ORDER BY m.activo DESC,e.nombre,m.nombre')->fetchAll(); }
    public static function localidadesAdmin(string $q=''): array { $db=Conexion::conectar();$where='';$params=[];if($q!==''){$where=' WHERE (l.nombre LIKE :q_localidad OR l.tipo LIKE :q_tipo OR m.nombre LIKE :q_municipio OR e.nombre LIKE :q_estado)';foreach(['q_localidad','q_tipo','q_municipio','q_estado'] as$k)$params[$k]='%'.$q.'%';}$count=$db->prepare('SELECT COUNT(*) FROM localidades l JOIN municipios m ON m.idMunicipio=l.idMunicipio JOIN estados e ON e.idEstado=m.idEstado'.$where);$count->execute($params);$stmt=$db->prepare('SELECT l.idLocalidad,l.idMunicipio,l.nombre,l.tipo,l.activo,m.nombre AS municipio,e.nombre AS estado,(SELECT COUNT(*) FROM sucursales s WHERE s.idLocalidad=l.idLocalidad) sucursales FROM localidades l JOIN municipios m ON m.idMunicipio=l.idMunicipio JOIN estados e ON e.idEstado=m.idEstado'.$where.' ORDER BY l.activo DESC,e.nombre,m.nombre,l.nombre LIMIT 200');$stmt->execute($params);return ['registros'=>$stmt->fetchAll(),'total'=>(int)$count->fetchColumn()]; }
    public static function resumenGeo(): array { return Conexion::conectar()->query('SELECT (SELECT COUNT(*) FROM estados) estados,(SELECT COUNT(*) FROM municipios) ciudades,(SELECT COUNT(*) FROM localidades) localidades,(SELECT COUNT(*) FROM municipios WHERE activo=1) ciudades_activas')->fetch()?:[]; }
    public static function estado(int $id): ?array { $s=Conexion::conectar()->prepare('SELECT * FROM estados WHERE idEstado=?');$s->execute([$id]);return$s->fetch()?:null; }
    public static function ciudad(int $id): ?array { $s=Conexion::conectar()->prepare('SELECT * FROM municipios WHERE idMunicipio=?');$s->execute([$id]);return$s->fetch()?:null; }
    public static function localidad(int $id): ?array { $s=Conexion::conectar()->prepare('SELECT * FROM localidades WHERE idLocalidad=?');$s->execute([$id]);return$s->fetch()?:null; }
    public static function estadosOpciones(): array { return Conexion::conectar()->query('SELECT idEstado,nombre,activo FROM estados ORDER BY activo DESC,nombre')->fetchAll(); }
    public static function ciudadesOpciones(): array { return Conexion::conectar()->query('SELECT m.idMunicipio,m.nombre,m.activo,e.nombre estado FROM municipios m JOIN estados e ON e.idEstado=m.idEstado ORDER BY m.activo DESC,e.nombre,m.nombre')->fetchAll(); }
    public static function estadoUsable(int $id): bool { $s=Conexion::conectar()->prepare('SELECT 1 FROM estados WHERE idEstado=? AND activo=1');$s->execute([$id]);return(bool)$s->fetchColumn(); }
    public static function estadoExiste(int $id): bool { $s=Conexion::conectar()->prepare('SELECT 1 FROM estados WHERE idEstado=?');$s->execute([$id]);return(bool)$s->fetchColumn(); }
    public static function ciudadUsable(int $id): bool { $s=Conexion::conectar()->prepare('SELECT 1 FROM municipios m JOIN estados e ON e.idEstado=m.idEstado WHERE m.idMunicipio=? AND m.activo=1 AND e.activo=1');$s->execute([$id]);return(bool)$s->fetchColumn(); }
    public static function ciudadExiste(int $id): bool { $s=Conexion::conectar()->prepare('SELECT 1 FROM municipios WHERE idMunicipio=?');$s->execute([$id]);return(bool)$s->fetchColumn(); }
    public static function guardarGeo(string $tipo,array $d): int { $db=Conexion::conectar();if($tipo==='estado'){if($d['id']){$db->prepare('UPDATE estados SET clave_inegi=?,nombre=?,activo=? WHERE idEstado=?')->execute([$d['clave'],$d['nombre'],$d['activo'],$d['id']]);return$d['id'];}$db->prepare('INSERT INTO estados(clave_inegi,nombre,activo) VALUES(?,?,?)')->execute([$d['clave'],$d['nombre'],$d['activo']]);return(int)$db->lastInsertId();}if($tipo==='ciudad'){if($d['id']){$db->prepare('UPDATE municipios SET idEstado=?,clave_inegi=?,nombre=?,activo=? WHERE idMunicipio=?')->execute([$d['parent'],$d['clave']?:null,$d['nombre'],$d['activo'],$d['id']]);return$d['id'];}$db->prepare('INSERT INTO municipios(idEstado,clave_inegi,nombre,activo) VALUES(?,?,?,?)')->execute([$d['parent'],$d['clave']?:null,$d['nombre'],$d['activo']]);return(int)$db->lastInsertId();}if($d['id']){$db->prepare('UPDATE localidades SET idMunicipio=?,nombre=?,tipo=?,activo=? WHERE idLocalidad=?')->execute([$d['parent'],$d['nombre'],$d['tipo']?:null,$d['activo'],$d['id']]);return$d['id'];}$db->prepare('INSERT INTO localidades(idMunicipio,nombre,tipo,activo) VALUES(?,?,?,?)')->execute([$d['parent'],$d['nombre'],$d['tipo']?:null,$d['activo']]);return(int)$db->lastInsertId(); }
    public static function estadoGeo(string $tipo,int $id,bool $activo): bool { $table=['estado'=>'estados','ciudad'=>'municipios','localidad'=>'localidades'][$tipo];$key=['estado'=>'idEstado','ciudad'=>'idMunicipio','localidad'=>'idLocalidad'][$tipo];$s=Conexion::conectar()->prepare("UPDATE $table SET activo=? WHERE $key=? AND activo<>?");$s->execute([$activo?1:0,$id,$activo?1:0]);return$s->rowCount()===1; }
}
