<?php
declare(strict_types=1);

final class ModeloSucursalesAdmin
{
    public static function listar(array $f,?array $alcance=null): array
    {
        $db=Conexion::conectar();$w=[];$p=[];
        if($f['q']!==''){$w[]='(s.nombre LIKE :q_nombre OR a.nombre_comercial LIKE :q_afiliado OR s.calle LIKE :q_calle OR s.colonia LIKE :q_colonia)';foreach(['q_nombre','q_afiliado','q_calle','q_colonia'] as$k)$p[$k]='%'.$f['q'].'%';}
        if($f['afiliado']){$w[]='s.idAfiliado=:afiliado';$p['afiliado']=$f['afiliado'];}
        if($f['estado']!==''){$w[]='s.activo=:activo';$p['activo']=(int)$f['estado'];}
        self::aplicarAlcance($w,$p,$alcance);
        $where=$w?' WHERE '.implode(' AND ',$w):'';$count=$db->prepare('SELECT COUNT(*) FROM sucursales s JOIN afiliados a ON a.idAfiliado=s.idAfiliado'.$where);$count->execute($p);$total=(int)$count->fetchColumn();
        $sql="SELECT s.idSucursal,s.idAfiliado,s.idLocalidad,s.nombre,s.es_matriz,s.calle,s.numero_exterior,s.numero_interior,s.colonia,s.codigo_postal,s.referencias,s.latitud,s.longitud,s.google_place_id,s.activo,a.nombre_comercial,l.nombre AS localidad,m.nombre AS municipio,e.nombre AS estado,
                    (SELECT st.numero_original FROM sucursales_telefonos st WHERE st.idSucursal=s.idSucursal AND st.tipo='TELEFONO' AND st.activo=1 ORDER BY st.es_principal DESC,st.idSucursalTelefono LIMIT 1) telefono,
                    (SELECT st.extension_telefono FROM sucursales_telefonos st WHERE st.idSucursal=s.idSucursal AND st.tipo='TELEFONO' AND st.activo=1 ORDER BY st.es_principal DESC,st.idSucursalTelefono LIMIT 1) extension_telefono,
                    (SELECT st.etiqueta FROM sucursales_telefonos st WHERE st.idSucursal=s.idSucursal AND st.tipo='TELEFONO' AND st.activo=1 ORDER BY st.es_principal DESC,st.idSucursalTelefono LIMIT 1) etiqueta,
                    (SELECT st.numero_original FROM sucursales_telefonos st WHERE st.idSucursal=s.idSucursal AND st.tipo='WHATSAPP' AND st.activo=1 ORDER BY st.es_principal DESC,st.idSucursalTelefono LIMIT 1) whatsapp,
                    (SELECT st.etiqueta FROM sucursales_telefonos st WHERE st.idSucursal=s.idSucursal AND st.tipo='WHATSAPP' AND st.activo=1 ORDER BY st.es_principal DESC,st.idSucursalTelefono LIMIT 1) etiqueta_whatsapp
             FROM sucursales s JOIN afiliados a ON a.idAfiliado=s.idAfiliado JOIN localidades l ON l.idLocalidad=s.idLocalidad JOIN municipios m ON m.idMunicipio=l.idMunicipio JOIN estados e ON e.idEstado=m.idEstado{$where} ORDER BY s.activo DESC,a.nombre_comercial,s.es_matriz DESC,s.nombre,s.idSucursal";
        $stmt=$db->prepare($sql);$stmt->execute($p);return ['registros'=>$stmt->fetchAll(),'total'=>$total];
    }
    public static function resumen(?array $alcance=null): array { $w=[];$p=[];self::aplicarAlcance($w,$p,$alcance);$s=Conexion::conectar()->prepare('SELECT COUNT(*) total,COALESCE(SUM(s.activo=1),0) activos,COALESCE(SUM(s.activo=0),0) inactivos,COUNT(DISTINCT s.idAfiliado) afiliados FROM sucursales s'.($w?' WHERE '.implode(' AND ',$w):''));$s->execute($p);return$s->fetch()?:[]; }
    public static function afiliados(?array $alcance=null): array { if($alcance===null)return Conexion::conectar()->query('SELECT idAfiliado,nombre_comercial,activo FROM afiliados ORDER BY activo DESC,nombre_comercial')->fetchAll();$ids=array_values(array_unique(array_filter(array_map('intval',$alcance),fn($id)=>$id>0)));if(!$ids)return[];$m=implode(',',array_fill(0,count($ids),'?'));$s=Conexion::conectar()->prepare("SELECT idAfiliado,nombre_comercial,activo FROM afiliados WHERE idAfiliado IN ($m) ORDER BY activo DESC,nombre_comercial");$s->execute($ids);return$s->fetchAll(); }
    public static function estados(): array { return Conexion::conectar()->query('SELECT idEstado,nombre FROM estados WHERE activo=1 ORDER BY nombre')->fetchAll(); }
    public static function obtener(int $id): ?array { $stmt=Conexion::conectar()->prepare("SELECT s.*,a.nombre_comercial,l.idMunicipio,m.idEstado,(SELECT st.numero_original FROM sucursales_telefonos st WHERE st.idSucursal=s.idSucursal AND st.tipo='TELEFONO' AND st.activo=1 ORDER BY st.es_principal DESC,st.idSucursalTelefono LIMIT 1) telefono,(SELECT st.extension_telefono FROM sucursales_telefonos st WHERE st.idSucursal=s.idSucursal AND st.tipo='TELEFONO' AND st.activo=1 ORDER BY st.es_principal DESC,st.idSucursalTelefono LIMIT 1) extension_telefono,(SELECT st.etiqueta FROM sucursales_telefonos st WHERE st.idSucursal=s.idSucursal AND st.tipo='TELEFONO' AND st.activo=1 ORDER BY st.es_principal DESC,st.idSucursalTelefono LIMIT 1) etiqueta,(SELECT st.numero_original FROM sucursales_telefonos st WHERE st.idSucursal=s.idSucursal AND st.tipo='WHATSAPP' AND st.activo=1 ORDER BY st.es_principal DESC,st.idSucursalTelefono LIMIT 1) whatsapp,(SELECT st.etiqueta FROM sucursales_telefonos st WHERE st.idSucursal=s.idSucursal AND st.tipo='WHATSAPP' AND st.activo=1 ORDER BY st.es_principal DESC,st.idSucursalTelefono LIMIT 1) etiqueta_whatsapp FROM sucursales s JOIN afiliados a ON a.idAfiliado=s.idAfiliado JOIN localidades l ON l.idLocalidad=s.idLocalidad JOIN municipios m ON m.idMunicipio=l.idMunicipio WHERE s.idSucursal=?");$stmt->execute([$id]);return $stmt->fetch()?:null; }
    public static function afiliadoUsable(int $id,?int $idSucursal): bool { $sql='SELECT 1 FROM afiliados WHERE idAfiliado=? AND (activo=1'.($idSucursal?' OR idAfiliado=(SELECT idAfiliado FROM sucursales WHERE idSucursal=?)':'').')';$s=Conexion::conectar()->prepare($sql);$s->execute($idSucursal?[$id,$idSucursal]:[$id]);return(bool)$s->fetchColumn(); }
    public static function localidadExiste(int $id): bool { $s=Conexion::conectar()->prepare('SELECT 1 FROM localidades l JOIN municipios m ON m.idMunicipio=l.idMunicipio JOIN estados e ON e.idEstado=m.idEstado WHERE l.idLocalidad=? AND l.activo=1 AND m.activo=1 AND e.activo=1');$s->execute([$id]);return(bool)$s->fetchColumn(); }
    public static function guardar(PDO $db,array $d): int
    {
        if($d['es_matriz'])$db->prepare('UPDATE sucursales SET es_matriz=0 WHERE idAfiliado=? AND es_matriz=1 AND activo=1 AND idSucursal<>?')->execute([$d['idAfiliado'],$d['id']??0]);
        if($d['id']){$s=$db->prepare('UPDATE sucursales SET idAfiliado=?,idLocalidad=?,nombre=?,es_matriz=?,calle=?,numero_exterior=?,numero_interior=?,colonia=?,codigo_postal=?,referencias=?,latitud=?,longitud=?,google_place_id=? WHERE idSucursal=?');$s->execute([$d['idAfiliado'],$d['idLocalidad'],$d['nombre']?:null,$d['es_matriz'],$d['calle'],$d['numero_exterior']?:null,$d['numero_interior']?:null,$d['colonia']?:null,$d['codigo_postal']?:null,$d['referencias']?:null,$d['latitud'],$d['longitud'],$d['google_place_id'],$d['id']]);$id=$d['id'];}
        else{$s=$db->prepare('INSERT INTO sucursales(idAfiliado,idLocalidad,nombre,es_matriz,calle,numero_exterior,numero_interior,colonia,codigo_postal,referencias,latitud,longitud,google_place_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->execute([$d['idAfiliado'],$d['idLocalidad'],$d['nombre']?:null,$d['es_matriz'],$d['calle'],$d['numero_exterior']?:null,$d['numero_interior']?:null,$d['colonia']?:null,$d['codigo_postal']?:null,$d['referencias']?:null,$d['latitud'],$d['longitud'],$d['google_place_id']]);$id=(int)$db->lastInsertId();}
        self::guardarTelefono($db,$id,'TELEFONO',$d['telefono'],true,$d['extension'],$d['etiqueta']);self::guardarTelefono($db,$id,'WHATSAPP',$d['whatsapp'],false,'',$d['etiqueta_whatsapp']);return$id;
    }
    private static function guardarTelefono(PDO $db,int $id,string $tipo,string $numero,bool $requerido,string $extension,string $etiqueta): void
    {
        $s=$db->prepare('SELECT idSucursalTelefono FROM sucursales_telefonos WHERE idSucursal=? AND tipo=? AND es_principal=1 ORDER BY activo DESC LIMIT 1');$s->execute([$id,$tipo]);$actual=$s->fetchColumn();$normal=preg_replace('/\D+/','',$numero)??'';
        if($numero===''){if($actual&&!$requerido)$db->prepare('UPDATE sucursales_telefonos SET activo=0 WHERE idSucursalTelefono=?')->execute([$actual]);return;}
        if($actual)$db->prepare('UPDATE sucursales_telefonos SET numero_original=?,numero_normalizado=?,extension_telefono=?,etiqueta=?,activo=1 WHERE idSucursalTelefono=?')->execute([$numero,$normal,$extension?:null,$etiqueta?:null,$actual]);else $db->prepare('INSERT INTO sucursales_telefonos(idSucursal,tipo,numero_original,numero_normalizado,extension_telefono,etiqueta,es_principal) VALUES(?,?,?,?,?,?,1)')->execute([$id,$tipo,$numero,$normal,$extension?:null,$etiqueta?:null]);
    }
    public static function cambiarEstado(int $id,bool $activo): bool { $s=Conexion::conectar()->prepare('UPDATE sucursales SET activo=? WHERE idSucursal=? AND activo<>?');$s->execute([$activo?1:0,$id,$activo?1:0]);return$s->rowCount()===1; }
    public static function perteneceAAlcance(int $id,array $alcance): bool { $ids=array_values(array_unique(array_filter(array_map('intval',$alcance),fn($v)=>$v>0)));if(!$ids)return false;$s=Conexion::conectar()->prepare('SELECT 1 FROM sucursales WHERE idSucursal=? AND idAfiliado IN ('.implode(',',array_fill(0,count($ids),'?')).')');$s->execute([$id,...$ids]);return(bool)$s->fetchColumn(); }
    private static function aplicarAlcance(array &$w,array &$p,?array $alcance): void { if($alcance===null)return;$ids=array_values(array_unique(array_filter(array_map('intval',$alcance),fn($id)=>$id>0)));if(!$ids){$w[]='1=0';return;}$n=[];foreach($ids as$i=>$id){$key='alcance'.$i;$n[]=':'.$key;$p[$key]=$id;}$w[]='s.idAfiliado IN ('.implode(',',$n).')'; }
}
