document.addEventListener('DOMContentLoaded',()=>{
 const modal=document.getElementById('modalPromocion'),form=document.getElementById('formPromocion'),toast=document.getElementById('notificacionPromocion');let cambio=null;
 const abrir=()=>{modal.hidden=false;requestAnimationFrame(()=>modal.classList.add('is-open'));};const cerrar=()=>{modal.classList.remove('is-open');setTimeout(()=>modal.hidden=true,180);};const aviso=(m,t='success')=>{toast.textContent=m;toast.className='canaco-toast is-'+t;toast.hidden=false;requestAnimationFrame(()=>toast.classList.add('is-visible'));setTimeout(()=>{toast.classList.remove('is-visible');setTimeout(()=>toast.hidden=true,180);},3500);};
 const limpiar=()=>{form.querySelectorAll('[data-error]').forEach(x=>x.textContent='');form.querySelectorAll('[aria-invalid]').forEach(x=>x.removeAttribute('aria-invalid'));};const errores=e=>Object.entries(e||{}).forEach(([k,v])=>{const x=form.elements[k],y=form.querySelector('[data-error="'+k+'"]');if(x)x.setAttribute('aria-invalid','true');if(y)y.textContent=v;});
 const fecha=v=>v?v.replace(' ','T').slice(0,16):'';const nuevo=()=>{form.reset();limpiar();document.getElementById('tituloModalPromocion').textContent='Registrar promoción';document.querySelector('#btnGuardarPromocion span').textContent='Guardar promoción';document.getElementById('archivosPromocion').innerHTML='';abrir();};
 document.getElementById('btnNuevaPromocion')?.addEventListener('click',nuevo);modal.querySelectorAll('[data-promo-close]').forEach(x=>x.addEventListener('click',cerrar));
 document.querySelectorAll('.btn-editar-promocion').forEach(b=>b.addEventListener('click',async()=>{try{const r=await canacoAjax('promociones/obtener',{id:b.dataset.id},'GET'),d=r.data;form.reset();limpiar();form.elements.idPromocion.value=d.idPromocion;form.elements.idAfiliado.value=d.idAfiliado;form.elements.titulo.value=d.titulo;form.elements.descripcion.value=d.descripcion;form.elements.restricciones.value=d.restricciones||'';form.elements.inicio_vigencia.value=fecha(d.inicio_vigencia);form.elements.fin_vigencia.value=fecha(d.fin_vigencia);document.getElementById('archivosPromocion').innerHTML=d.archivos?.length?'<strong>Imágenes actuales ('+d.archivos.length+'/5)</strong><ul>'+d.archivos.map(x=>'<li>'+escapar(x.nombre_original)+'</li>').join('')+'</ul>':'';document.getElementById('tituloModalPromocion').textContent='Editar promoción';document.querySelector('#btnGuardarPromocion span').textContent='Guardar cambios';abrir();}catch(e){aviso(e.message,'error');}}));
 form.addEventListener('submit',async e=>{e.preventDefault();limpiar();const f=document.getElementById('promoGaleria').files;if(f.length>5){errores({galeria:'Selecciona máximo cinco imágenes.'});return;}const b=document.getElementById('btnGuardarPromocion');b.disabled=true;try{const r=await canacoAjax('promociones/guardar',new FormData(form),'POST');sessionStorage.setItem('canaco_mensaje',r.message);location.reload();}catch(x){errores(x.errors);aviso(x.message,'error');}finally{b.disabled=false;}});
 document.querySelectorAll('.btn-estado-promocion').forEach(b=>b.addEventListener('click',async()=>{const activar=b.dataset.activo==='1';if(!confirm((activar?'Activar':'Desactivar')+' la promoción “'+b.dataset.titulo+'”?'))return;try{const r=await canacoAjax('promociones/cambiar-estado',{idPromocion:b.dataset.id,activo:activar},'POST');sessionStorage.setItem('canaco_mensaje',r.message);location.reload();}catch(e){aviso(e.message,'error');}}));
 const m=sessionStorage.getItem('canaco_mensaje');if(m){sessionStorage.removeItem('canaco_mensaje');aviso(m);}document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)cerrar();});
});
function escapar(v){const x=document.createElement('div');x.textContent=v||'';return x.innerHTML;}
