document.addEventListener('DOMContentLoaded',()=>{
 const modal=document.getElementById('modalUsuario'),form=document.getElementById('formUsuario'),toast=document.getElementById('notificacionUsuario'),rol=document.getElementById('usuarioRol'),grupoCamara=document.getElementById('grupoCamara'),grupoAfiliados=document.getElementById('grupoAfiliados');
 const abrir=()=>window.canacoMotion.open(modal),cerrar=()=>window.canacoMotion.close(modal);
 const aviso=(mensaje,tipo='success')=>{toast.textContent=mensaje;toast.className='canaco-toast is-'+tipo;toast.hidden=false;requestAnimationFrame(()=>toast.classList.add('is-visible'));setTimeout(()=>{toast.classList.remove('is-visible');setTimeout(()=>toast.hidden=true,180);},3500);};
 const limpiar=()=>{form.querySelectorAll('[data-error]').forEach(x=>x.textContent='');form.querySelectorAll('[aria-invalid]').forEach(x=>x.removeAttribute('aria-invalid'));};
 const errores=datos=>Object.entries(datos||{}).forEach(([campo,mensaje])=>{const entrada=form.elements[campo],destino=form.querySelector('[data-error="'+campo+'"]');if(entrada)entrada.setAttribute('aria-invalid','true');if(destino)destino.textContent=mensaje;});
 const actualizarPerfil=()=>{const clave=rol.options[rol.selectedIndex]?.dataset.clave||'';grupoCamara.hidden=clave!=='ADMIN_CAMARA';grupoAfiliados.hidden=clave!=='AFILIADO';if(clave!=='ADMIN_CAMARA')form.elements.idCamara.value='';if(clave!=='AFILIADO')form.querySelectorAll('[name="afiliados[]"]').forEach(x=>x.checked=false);};
 const nuevo=()=>{form.reset();limpiar();actualizarPerfil();form.elements.password.required=true;form.elements.password_confirmacion.required=true;document.getElementById('textoPassword').textContent='*';document.getElementById('textoPasswordConfirmacion').textContent='*';document.getElementById('ayudaPassword').textContent='Mínimo 10 caracteres, incluyendo letras y números.';document.getElementById('tituloModalUsuario').textContent='Registrar usuario';document.querySelector('#btnGuardarUsuario span').textContent='Guardar usuario';abrir();};
 rol.addEventListener('change',actualizarPerfil);document.getElementById('btnNuevoUsuario').addEventListener('click',nuevo);modal.querySelectorAll('[data-usuario-close]').forEach(x=>x.addEventListener('click',cerrar));
 document.querySelectorAll('.btn-editar-usuario').forEach(b=>b.addEventListener('click',async()=>{try{const r=await canacoAjax('usuarios/obtener',{id:b.dataset.id},'GET'),d=r.data;form.reset();limpiar();form.elements.idUsuario.value=d.idUsuario;form.elements.nombre.value=d.nombre;form.elements.correo.value=d.correo;form.elements.idRol.value=d.idRol;form.elements.activo.value=d.activo;form.elements.idCamara.value=d.idCamara||'';form.querySelectorAll('[name="afiliados[]"]').forEach(x=>x.checked=(d.afiliados||[]).map(Number).includes(Number(x.value)));actualizarPerfil();form.elements.idCamara.value=d.idCamara||'';form.querySelectorAll('[name="afiliados[]"]').forEach(x=>x.checked=(d.afiliados||[]).map(Number).includes(Number(x.value)));form.elements.password.required=false;form.elements.password_confirmacion.required=false;document.getElementById('textoPassword').textContent='(opcional)';document.getElementById('textoPasswordConfirmacion').textContent='(opcional)';document.getElementById('ayudaPassword').textContent='Déjala vacía para conservar la contraseña actual.';document.getElementById('tituloModalUsuario').textContent='Editar usuario';document.querySelector('#btnGuardarUsuario span').textContent='Guardar cambios';abrir();}catch(error){aviso(error.message,'error');}}));
 form.addEventListener('submit',async evento=>{evento.preventDefault();limpiar();const boton=document.getElementById('btnGuardarUsuario');boton.disabled=true;try{const r=await canacoAjax('usuarios/guardar',new FormData(form),'POST');sessionStorage.setItem('canaco_mensaje',r.message);location.reload();}catch(error){errores(error.errors);aviso(error.message,'error');}finally{boton.disabled=false;}});
 document.querySelectorAll('.btn-estado-usuario').forEach(b=>b.addEventListener('click',async()=>{const activar=b.dataset.activo==='1';if(!confirm((activar?'Activar':'Desactivar')+' al usuario “'+b.dataset.nombre+'”?'))return;try{const r=await canacoAjax('usuarios/cambiar-estado',{idUsuario:b.dataset.id,activo:activar},'POST');sessionStorage.setItem('canaco_mensaje',r.message);location.reload();}catch(error){aviso(error.message,'error');}}));
 const mensaje=sessionStorage.getItem('canaco_mensaje');if(mensaje){sessionStorage.removeItem('canaco_mensaje');aviso(mensaje);}document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)cerrar();});
});
