<?php
$listado=$datosVista['listado']??['registros'=>[],'total'=>0,'pagina'=>1,'paginas'=>1];$afiliados=$listado['registros'];$estadisticas=$datosVista['estadisticas']??[];$camaras=$datosVista['camaras']??[];$estados=$datosVista['estados']??[];$localidadesFiltro=$datosVista['localidadesFiltro']??[];$categorias=$datosVista['categorias']??[];$filtros=$datosVista['filtros']??['busqueda'=>'','estado'=>'','camara'=>0,'localidad'=>0,'categoria'=>0];
?>
<section aria-labelledby="titulo-panel">
 <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-6"><div><h2 id="titulo-panel" class="text-2xl font-semibold text-foreground">Panel de afiliados</h2><p class="mt-1 text-sm text-muted-foreground">Administra el directorio comercial y la información pública de cada empresa.</p></div><button type="button" class="kt-btn kt-btn-primary shrink-0" id="btnNuevoAfiliado"><i class="ki-filled ki-plus"></i><span>Registrar afiliado</span></button></div>
 <div class="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-6"><?php foreach([['Total registrados','total','ki-people','primary'],['Activos','activos','ki-check-circle','success'],['Inactivos','inactivos','ki-information-2','danger'],['Cámaras','camaras','ki-bank','info']]as[$etiqueta,$campo,$icono,$color]): ?><article class="kt-card canaco-stat-card"><div class="kt-card-body p-5"><span class="text-sm text-muted-foreground"><?= $etiqueta ?></span><div class="flex items-end justify-between mt-2"><strong class="text-3xl text-foreground"><?= (int)($estadisticas[$campo]??0) ?></strong><span class="canaco-stat-icon bg-<?= $color ?>/10 text-<?= $color ?>"><i class="ki-filled <?= $icono ?>"></i></span></div></div></article><?php endforeach; ?></div>
 <div class="kt-card">
  <div class="kt-card-header flex-wrap gap-3 py-4 min-h-0"><div class="canaco-directory-toolbar"><div><h3 class="font-semibold text-foreground">Directorio de afiliados</h3><p class="text-sm text-muted-foreground">Busca, filtra o registra una empresa.</p></div><button type="button" class="kt-btn kt-btn-primary shrink-0" id="btnNuevoAfiliado"><i class="ki-filled ki-plus"></i><span>Registrar afiliado</span></button></div><form class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-7 gap-3 w-full mt-4" action="<?= base_url('afiliados') ?>" method="get" role="search">
   <label class="kt-input xl:col-span-2"><i class="ki-filled ki-magnifier"></i><input type="search" name="q" value="<?= e($filtros['busqueda']) ?>" placeholder="Nombre, alias, razón social o RFC" aria-label="Buscar afiliados"></label>
   <select class="kt-select" name="camara" aria-label="Filtrar por cámara"><option value="">Todas las cámaras</option><?php foreach($camaras as$c):?><option value="<?= (int)$c['idCamara'] ?>" <?= (int)$filtros['camara']===(int)$c['idCamara']?'selected':'' ?>><?= e($c['nombre']) ?></option><?php endforeach;?></select>
   <select class="kt-select" name="categoria" aria-label="Filtrar por categoría"><option value="">Todas las categorías</option><?php foreach($categorias as$c):?><option value="<?= (int)$c['idCategoria'] ?>" <?= (int)$filtros['categoria']===(int)$c['idCategoria']?'selected':'' ?>><?= e($c['nombre']) ?></option><?php endforeach;?></select>
   <select class="kt-select" name="estado" aria-label="Filtrar por estado"><option value="">Todos los estatus</option><option value="1" <?= $filtros['estado']==='1'?'selected':'' ?>>Activos</option><option value="0" <?= $filtros['estado']==='0'?'selected':'' ?>>Inactivos</option></select><button class="kt-btn kt-btn-light" type="submit">Filtrar</button>
   <select class="kt-select" name="localidad" aria-label="Filtrar por ciudad o localidad"><option value="">Todas las ciudades</option><?php foreach($localidadesFiltro as$l):?><option value="<?= (int)$l['idLocalidad'] ?>" <?= (int)$filtros['localidad']===(int)$l['idLocalidad']?'selected':'' ?>><?= e($l['nombre']) ?></option><?php endforeach;?></select>
  </form></div>
  <div class="overflow-x-auto"><table class="kt-table canaco-table"><thead><tr><th>Afiliado</th><th>RFC</th><th>Cámara</th><th>Ciudad / Categoría</th><th>Contacto</th><th>Estado</th><th class="text-end"><span class="sr-only">Acciones</span></th></tr></thead><tbody>
   <?php foreach($afiliados as$a):?><tr><td><div class="flex items-center gap-3"><span class="canaco-avatar"><?= e(mb_strtoupper(mb_substr($a['nombre_comercial'],0,1))) ?></span><div><div class="font-medium text-foreground"><?= e($a['nombre_comercial']) ?></div><div class="text-xs text-muted-foreground"><?= e($a['alias']?:($a['razon_social']?:'Sin alias')) ?></div></div></div></td><td class="font-mono text-xs"><?= e($a['rfc']) ?></td><td><?= e($a['camara_nombre']) ?></td><td><div class="text-sm"><?= e($a['localidad_nombre']?:'Sin ubicación') ?></div><div class="text-xs text-muted-foreground"><?= e($a['categoria_nombre']?:'Sin categoría') ?></div></td><td><?= $a['correo_general']?'<a class="text-primary hover:underline" href="mailto:'.e($a['correo_general']).'">'.e($a['correo_general']).'</a>':'<span class="text-muted-foreground">Sin correo</span>' ?></td><td><?= (int)$a['activo']===1?'<span class="kt-badge kt-badge-success kt-badge-outline">Activo</span>':'<span class="kt-badge kt-badge-danger kt-badge-outline">Inactivo</span>' ?></td><td class="text-end whitespace-nowrap"><button type="button" class="kt-btn kt-btn-sm kt-btn-icon kt-btn-ghost btn-editar" data-id="<?= (int)$a['idAfiliado'] ?>" aria-label="Editar <?= e($a['nombre_comercial']) ?>"><i class="ki-filled ki-pencil"></i></button><button type="button" class="kt-btn kt-btn-sm kt-btn-icon kt-btn-ghost btn-estado" data-id="<?= (int)$a['idAfiliado'] ?>" data-nombre="<?= e($a['nombre_comercial']) ?>" data-activo="<?= (int)$a['activo']===1?'0':'1' ?>" aria-label="Cambiar estado de <?= e($a['nombre_comercial']) ?>"><i class="ki-filled <?= (int)$a['activo']===1?'ki-toggle-on-circle':'ki-toggle-off-circle' ?>"></i></button></td></tr><?php endforeach;?>
   <?php if(!$afiliados):?><tr><td colspan="7"><div class="canaco-empty"><span class="canaco-empty-icon"><i class="ki-filled ki-search-list"></i></span><strong>No encontramos afiliados</strong><p>Prueba con otros filtros o registra una nueva empresa.</p></div></td></tr><?php endif;?>
  </tbody></table></div><div class="kt-card-footer py-4"><span class="text-sm text-muted-foreground"><?= (int)$listado['total'] ?> resultado<?= (int)$listado['total']===1?'':'s' ?></span></div>
 </div>
</section>

<div class="canaco-modal" id="modalAfiliado" hidden aria-hidden="true"><div class="canaco-modal-backdrop" data-modal-close></div><div class="canaco-modal-dialog canaco-modal-xl" role="dialog" aria-modal="true" aria-labelledby="modalTitulo"><form id="formAfiliado" enctype="multipart/form-data" novalidate><input type="hidden" name="csrf_token" value="<?= e(obtenerTokenCSRF()) ?>">
 <div class="canaco-modal-header"><div><h3 class="text-lg font-semibold" id="modalTitulo">Registrar afiliado</h3><p class="text-sm text-muted-foreground mt-1">La información con * es obligatoria para publicar el afiliado.</p></div><button type="button" class="kt-btn kt-btn-icon kt-btn-ghost" data-modal-close aria-label="Cerrar"><i class="ki-filled ki-cross"></i></button></div>
 <div class="canaco-modal-body p-0"><input type="hidden" name="idAfiliado"><div class="canaco-form-nav" role="tablist"><button type="button" class="is-active" data-section="general">1. Generales</button><button type="button" data-section="contacto">2. Contacto y ubicación</button><button type="button" data-section="digital">3. Canales digitales</button><button type="button" data-section="comercial">4. Comercial y archivos</button></div><div class="p-6">
  <fieldset class="canaco-form-section" data-section-panel="general"><legend>Datos generales</legend><div class="grid grid-cols-1 md:grid-cols-2 gap-5">
   <div class="canaco-field"><label for="idCamara">Cámara *</label><select class="kt-select" id="idCamara" name="idCamara" required><option value="">Selecciona una cámara</option><?php foreach($camaras as$c):?><option value="<?= (int)$c['idCamara'] ?>"><?= e($c['nombre']) ?></option><?php endforeach;?></select><span data-error="idCamara"></span></div><div class="canaco-field"><label for="rfc">RFC *</label><input class="kt-input uppercase font-mono" id="rfc" name="rfc" maxlength="13" required><span data-error="rfc"></span></div>
   <div class="canaco-field"><label for="nombre_comercial">Nombre comercial *</label><input class="kt-input" id="nombre_comercial" name="nombre_comercial" maxlength="180" required><span data-error="nombre_comercial"></span></div><div class="canaco-field"><label for="razon_social">Razón social</label><input class="kt-input" id="razon_social" name="razon_social" maxlength="180"></div>
   <div class="canaco-field"><label for="alias">Alias público</label><input class="kt-input" id="alias" name="alias" maxlength="120"></div><div class="canaco-field"><label for="correo_general">Correo electrónico *</label><input class="kt-input" id="correo_general" name="correo_general" type="email" maxlength="254" required><span data-error="correo_general"></span></div>
  </div><div class="canaco-field mt-5"><label for="descripcion">Descripción pública *</label><textarea class="kt-input min-h-28" id="descripcion" name="descripcion" maxlength="5000" required></textarea><span data-error="descripcion"></span></div></fieldset>
  <fieldset class="canaco-form-section hidden" data-section-panel="contacto"><legend>Contacto, domicilio y mapa</legend><div class="grid grid-cols-1 md:grid-cols-2 gap-5">
   <div class="canaco-field"><label for="encargado">Nombre del encargado *</label><input class="kt-input" id="encargado" name="encargado" maxlength="160"><span data-error="encargado"></span></div><div class="canaco-field"><label for="cargo_encargado">Cargo</label><input class="kt-input" id="cargo_encargado" name="cargo_encargado" maxlength="100"></div>
   <div class="canaco-field"><label for="telefono">Teléfono *</label><input class="kt-input" id="telefono" name="telefono" maxlength="50"><span data-error="telefono"></span></div><div class="canaco-field"><label for="whatsapp">WhatsApp</label><input class="kt-input" id="whatsapp" name="whatsapp" maxlength="50"></div>
   <div class="canaco-field"><label for="idEstado">Estado *</label><select class="kt-select" id="idEstado" name="idEstado"><option value="">Selecciona un estado</option><?php foreach($estados as$e):?><option value="<?= (int)$e['idEstado'] ?>"><?= e($e['nombre']) ?></option><?php endforeach;?></select></div><div class="canaco-field"><label for="idMunicipio">Municipio *</label><select class="kt-select" id="idMunicipio" name="idMunicipio" disabled><option value="">Primero selecciona un estado</option></select></div>
   <div class="canaco-field"><label for="idLocalidad">Ciudad / localidad *</label><select class="kt-select" id="idLocalidad" name="idLocalidad" disabled><option value="">Primero selecciona un municipio</option></select><span data-error="idLocalidad"></span></div><div class="canaco-field"><label for="calle">Calle *</label><input class="kt-input" id="calle" name="calle" maxlength="160"><span data-error="calle"></span></div>
   <div class="canaco-field"><label for="numero_exterior">Número exterior</label><input class="kt-input" id="numero_exterior" name="numero_exterior" maxlength="20"></div><div class="canaco-field"><label for="numero_interior">Número interior</label><input class="kt-input" id="numero_interior" name="numero_interior" maxlength="20"></div>
   <div class="canaco-field"><label for="colonia">Colonia</label><input class="kt-input" id="colonia" name="colonia" maxlength="130"></div><div class="canaco-field"><label for="codigo_postal">Código postal</label><input class="kt-input" id="codigo_postal" name="codigo_postal" maxlength="5" inputmode="numeric"><span data-error="codigo_postal"></span></div>
   <div class="canaco-field"><label for="latitud">Latitud</label><input class="kt-input" id="latitud" name="latitud" inputmode="decimal"><span data-error="latitud"></span></div><div class="canaco-field"><label for="longitud">Longitud</label><input class="kt-input" id="longitud" name="longitud" inputmode="decimal"></div>
  </div><div class="canaco-field mt-5"><label for="referencias">Referencias</label><input class="kt-input" id="referencias" name="referencias" maxlength="500"></div><div class="canaco-field mt-5"><label for="google_place_id">Google Place ID</label><input class="kt-input" id="google_place_id" name="google_place_id" maxlength="255"></div></fieldset>
  <fieldset class="canaco-form-section hidden" data-section-panel="digital"><legend>Canales digitales</legend><p class="text-sm text-muted-foreground mb-5">Captura URLs completas, incluyendo <code>https://</code>.</p><div class="grid grid-cols-1 md:grid-cols-3 gap-5"><div class="canaco-field"><label for="facebook">Facebook</label><input class="kt-input" id="facebook" name="facebook" type="url" placeholder="https://facebook.com/..."><span data-error="facebook"></span></div><div class="canaco-field"><label for="instagram">Instagram</label><input class="kt-input" id="instagram" name="instagram" type="url" placeholder="https://instagram.com/..."><span data-error="instagram"></span></div><div class="canaco-field"><label for="sitio_web">Sitio web</label><input class="kt-input" id="sitio_web" name="sitio_web" type="url" placeholder="https://..."><span data-error="sitio_web"></span></div></div></fieldset>
  <fieldset class="canaco-form-section hidden" data-section-panel="comercial"><legend>Clasificación y archivos</legend><div class="canaco-field"><label>Categorías comerciales *</label><div class="canaco-category-list" id="listaCategorias"><?php if(!$categorias):?><p class="text-sm text-warning">No hay categorías activas. Carga el catálogo antes de registrar afiliados.</p><?php else:foreach($categorias as$c):?><label><input type="checkbox" name="categorias[]" value="<?= (int)$c['idCategoria'] ?>"> <?= e($c['nombre']) ?></label><?php endforeach;endif;?></div><span data-error="categorias"></span></div><div class="canaco-field mt-5"><label for="palabras_clave">Palabras clave</label><textarea class="kt-input min-h-24" id="palabras_clave" name="palabras_clave" maxlength="809" placeholder="Separadas por coma. Máximo 10."></textarea><span data-error="palabras_clave"></span></div><div class="grid grid-cols-1 md:grid-cols-2 gap-5 mt-5"><div class="canaco-field"><label for="logo">Logotipo *</label><input class="kt-input" id="logo" name="logo" type="file" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG o WEBP; máximo 2 MB.</small><span data-error="logo"></span></div><div class="canaco-field"><label for="galeria">Galería</label><input class="kt-input" id="galeria" name="galeria[]" type="file" accept="image/jpeg,image/png,image/webp" multiple><small>Hasta 10 imágenes por carga, 2 MB cada una.</small></div></div><div id="archivosActuales" class="canaco-file-summary mt-5"></div></fieldset>
 </div></div><div class="canaco-modal-footer"><button type="button" class="kt-btn kt-btn-ghost" id="btnAnteriorAfiliado" hidden><i class="ki-filled ki-arrow-left"></i>Anterior</button><span class="grow"></span><button type="button" class="kt-btn kt-btn-light" data-modal-close>Cancelar</button><button type="submit" class="kt-btn kt-btn-primary" id="btnGuardarAfiliado"><span data-button-label>Siguiente</span><i class="ki-filled ki-arrow-right" data-next-icon></i></button></div>
</form></div></div>
<div class="canaco-modal" id="modalEstado" hidden aria-hidden="true"><div class="canaco-modal-backdrop" data-status-close></div><div class="canaco-modal-dialog max-w-md" role="dialog" aria-modal="true" aria-labelledby="estadoTitulo"><form id="formEstado"><div class="canaco-modal-header"><div><h3 class="text-lg font-semibold" id="estadoTitulo">Cambiar estado</h3><p class="text-sm text-muted-foreground mt-1" id="estadoDescripcion"></p></div></div><div class="canaco-modal-body"><div class="canaco-field" id="grupoMotivo"><label for="motivoEstado">Motivo de desactivación</label><textarea class="kt-input min-h-24" id="motivoEstado" maxlength="500" placeholder="Opcional"></textarea></div></div><div class="canaco-modal-footer"><button type="button" class="kt-btn kt-btn-light" data-status-close>Cancelar</button><button type="submit" class="kt-btn kt-btn-primary" id="btnConfirmarEstado">Confirmar</button></div></form></div></div>
<div class="canaco-toast" id="notificacion" role="status" aria-live="polite" hidden></div>
