<?php
declare(strict_types=1);

final class ControladorCategorias extends ControladorCatalogosAdmin
{
    public function index(): array { $this->autorizar('categorias.gestionar');$f=['q'=>mb_substr(trim((string)($_GET['q']??'')),0,100),'estado'=>in_array((string)($_GET['estado']??''),['0','1'],true)?(string)$_GET['estado']:''];return ['filtros'=>$f,'listado'=>ModeloCatalogosAdmin::categorias($f),'estadisticas'=>ModeloCatalogosAdmin::resumenCategorias(),'padres'=>ModeloCatalogosAdmin::padres()]; }
    public function obtener(): never { $this->autorizar('categorias.gestionar');$this->metodo('GET');$d=ModeloCatalogosAdmin::categoria($this->idGet());if(!$d)$this->json(['status'=>'error','message'=>'La categoría no existe.'],404);$this->json(['status'=>'success','data'=>$d]); }
    public function guardar(): never
    {
        $this->autorizar('categorias.gestionar');$this->metodo('POST');$in=$this->entrada();$this->csrf($in);$raw=empty($in['idCategoria'])?null:filter_var($in['idCategoria'],FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$id=$raw?:null;$parent=empty($in['idCategoriaPadre'])?null:(int)$in['idCategoriaPadre'];$nombre=mb_substr(trim((string)($in['nombre']??'')),0,120);$desc=mb_substr(trim((string)($in['descripcion']??'')),0,500);$activo=(string)($in['activo']??'1')==='0'?0:1;$slug=$this->slug((string)($in['slug']??''),$nombre);$errors=[];
        if($nombre==='')$errors['nombre']='El nombre es obligatorio.';if($slug===''||mb_strlen($slug)>150)$errors['slug']='Captura un slug válido (máximo 150 caracteres).';if($parent&&!ModeloCatalogosAdmin::categoria($parent))$errors['idCategoriaPadre']='Selecciona una categoría padre existente.';if($id&&$parent&&($id===$parent||ModeloCatalogosAdmin::esDescendiente($parent,$id)))$errors['idCategoriaPadre']='La jerarquía no puede formar un ciclo.';if(ModeloCatalogosAdmin::slugExiste($slug,$id))$errors['slug']='Este slug ya está registrado.';if(ModeloCatalogosAdmin::nombreExiste($nombre,$parent,$id))$errors['nombre']='Ya existe una categoría con este nombre dentro del nivel seleccionado.';if($errors)$this->json(['status'=>'error','message'=>'Revisa los campos marcados.','errors'=>$errors],422);
        try{$id=ModeloCatalogosAdmin::guardarCategoria(['id'=>$id,'padre'=>$parent,'nombre'=>$nombre,'slug'=>$slug,'descripcion'=>$desc,'activo'=>$activo]);}catch(Throwable $e){registrarLog('Error al guardar categoría: '.$e->getMessage(),'ERROR');$this->json(['status'=>'error','message'=>'No fue posible guardar la categoría. Verifica sus datos y las relaciones existentes.'],500);}$this->json(['status'=>'success','message'=>$raw?'Categoría actualizada correctamente.':'Categoría registrada correctamente.','data'=>['idCategoria'=>$id]],$raw?200:201);
    }
    public function cambiarEstado(): never { $this->autorizar('categorias.gestionar');$this->metodo('POST');$in=$this->entrada();$this->csrf($in);$id=filter_var($in['idCategoria']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$activo=filter_var($in['activo']??null,FILTER_VALIDATE_BOOLEAN,FILTER_NULL_ON_FAILURE);if(!$id||$activo===null)$this->json(['status'=>'error','message'=>'Datos no válidos.'],422);if(!ModeloCatalogosAdmin::estadoCategoria((int)$id,$activo))$this->json(['status'=>'error','message'=>'La categoría no existe o ya tiene ese estado.'],404);$this->json(['status'=>'success','message'=>$activo?'Categoría activada.':'Categoría desactivada.']); }
    private function slug(string $valor,string $fallback): string { $valor=trim($valor)?:$fallback;$valor=mb_strtolower($valor);$valor=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',$valor)?:$valor;$valor=preg_replace('/[^a-z0-9]+/','-',strtolower($valor))??'';return trim($valor,'-'); }
}
