<?php
declare(strict_types=1);

final class ControladorCiudades extends ControladorCatalogosAdmin
{
    public function index(): array { $this->autorizar(null);$f=['q'=>mb_substr(trim((string)($_GET['q']??'')),0,100)];$needle=mb_strtolower($f['q']);$filter=static fn(array $rows,string $keys):array=>$needle===''?$rows:array_values(array_filter($rows,static function($r)use($needle,$keys){foreach(explode('|',$keys) as$k)if(str_contains(mb_strtolower((string)($r[$k]??'')),$needle))return true;return false;}));return ['filtros'=>$f,'estados'=>$filter(ModeloCatalogosAdmin::estados(),'nombre|clave_inegi'),'ciudades'=>$filter(ModeloCatalogosAdmin::ciudades(),'nombre|estado|clave_inegi'),'localidades'=>ModeloCatalogosAdmin::localidadesAdmin($f['q']),'estadisticas'=>ModeloCatalogosAdmin::resumenGeo(),'opciones'=>['estados'=>ModeloCatalogosAdmin::estadosOpciones(),'ciudades'=>ModeloCatalogosAdmin::ciudadesOpciones()]]; }
    public function obtener(): never { $this->autorizar(null);$this->metodo('GET');$tipo=(string)($_GET['tipo']??'');$id=$this->idGet();$fn=['estado'=>'estado','ciudad'=>'ciudad','localidad'=>'localidad'][$tipo]??null;if(!$fn)$this->json(['status'=>'error','message'=>'Tipo de ubicación inválido.'],422);$d=ModeloCatalogosAdmin::$fn($id);if(!$d)$this->json(['status'=>'error','message'=>'El registro no existe.'],404);$this->json(['status'=>'success','data'=>$d]); }
    public function guardar(): never
    {
        $this->autorizar(null);$this->metodo('POST');$in=$this->entrada();$this->csrf($in);$tipo=(string)($in['tipo']??'');if(!in_array($tipo,['estado','ciudad','localidad'],true))$this->json(['status'=>'error','message'=>'Tipo de ubicación inválido.'],422);$raw=empty($in['id'])?null:filter_var($in['id'],FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if($raw===false)$this->json(['status'=>'error','message'=>'Identificador inválido.'],422);$id=$raw?:null;$current=$id?match($tipo){'estado'=>ModeloCatalogosAdmin::estado((int)$id),'ciudad'=>ModeloCatalogosAdmin::ciudad((int)$id),'localidad'=>ModeloCatalogosAdmin::localidad((int)$id)}:null;if($id&&!$current)$this->json(['status'=>'error','message'=>'El registro no existe.'],404);$nombre=mb_substr(trim((string)($in['nombre']??'')),0,$tipo==='localidad'?150:120);$clave=trim((string)($in['clave_inegi']??''));$parent=(int)($in['parent']??($current['idEstado']??$current['idMunicipio']??0));$subtipo=mb_substr(trim((string)($in['subtipo']??'')),0,40);$activo=(string)($in['activo']??'1')==='0'?0:1;$errors=[];if($nombre==='')$errors['nombre']='El nombre es obligatorio.';
        if($tipo==='estado'&&!preg_match('/^\d{2}$/',$clave))$errors['clave_inegi']='La clave INEGI del estado debe tener dos dígitos.';if($tipo==='ciudad'&&$clave!==''&&!preg_match('/^\d{1,5}$/',$clave))$errors['clave_inegi']='La clave INEGI de la ciudad debe tener hasta cinco dígitos.';if($tipo==='ciudad'&&!ModeloCatalogosAdmin::estadoUsable($parent)&&!($current&&(int)$current['idEstado']===$parent&&ModeloCatalogosAdmin::estadoExiste($parent)))$errors['parent']='Selecciona un estado activo.';if($tipo==='localidad'&&!ModeloCatalogosAdmin::ciudadUsable($parent)&&!($current&&(int)$current['idMunicipio']===$parent&&ModeloCatalogosAdmin::ciudadExiste($parent)))$errors['parent']='Selecciona una ciudad activa.';
        if($errors)$this->json(['status'=>'error','message'=>'Revisa los campos marcados.','errors'=>$errors],422);try{$newId=ModeloCatalogosAdmin::guardarGeo($tipo,['id'=>$id,'parent'=>$parent,'nombre'=>$nombre,'clave'=>$clave,'tipo'=>$subtipo,'activo'=>$activo]);}catch(Throwable $e){registrarLog('Error al guardar catálogo geográfico: '.$e->getMessage(),'ERROR');$this->json(['status'=>'error','message'=>'No fue posible guardar el registro. Revisa que su nombre o clave no estén duplicados.'],500);}$label=['estado'=>'Estado','ciudad'=>'Ciudad','localidad'=>'Localidad'][$tipo];$this->json(['status'=>'success','message'=>$raw?$label.' actualizado correctamente.':$label.' registrado correctamente.','data'=>['id'=>$newId]],$raw?200:201);
    }
    public function cambiarEstado(): never { $this->autorizar(null);$this->metodo('POST');$in=$this->entrada();$this->csrf($in);$tipo=(string)($in['tipo']??'');$id=filter_var($in['id']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$activo=filter_var($in['activo']??null,FILTER_VALIDATE_BOOLEAN,FILTER_NULL_ON_FAILURE);if(!in_array($tipo,['estado','ciudad','localidad'],true)||!$id||$activo===null)$this->json(['status'=>'error','message'=>'Datos no válidos.'],422);if(!ModeloCatalogosAdmin::estadoGeo($tipo,(int)$id,$activo))$this->json(['status'=>'error','message'=>'El registro no existe o ya tiene ese estado.'],404);$label=['estado'=>'Estado','ciudad'=>'Ciudad','localidad'=>'Localidad'][$tipo];$this->json(['status'=>'success','message'=>$label.($activo?' activado.':' desactivado.')]); }
}
