<?php
declare(strict_types=1);
final class ControladorPromociones
{
 public function index():array{$f=['q'=>mb_substr(trim((string)($_GET['q']??'')),0,100),'afiliado'=>max(0,(int)($_GET['afiliado']??0)),'estado'=>in_array((string)($_GET['estado']??''),['0','1'],true)?(string)$_GET['estado']:'' ];return['filtros'=>$f,'listado'=>ModeloPromociones::listar($f,max(1,(int)($_GET['pagina']??1))),'estadisticas'=>ModeloPromociones::estadisticas(),'afiliados'=>ModeloPromociones::afiliadosActivos()];}
 public function obtener():void{$this->metodo('GET');$r=ModeloPromociones::obtener($this->idGet('id'));if(!$r)$this->json(['status'=>'error','message'=>'La promoción no existe.'],404);$this->json(['status'=>'success','data'=>$r]);}
 public function guardar():void{$this->metodo('POST');$this->csrf($_POST);$d=$this->normalizar($_POST);$e=$this->validar($d);$nuevas=$this->archivosEntrada($_FILES['galeria']??null);$existentes=$d['idPromocion']?ModeloPromociones::totalImagenes($d['idPromocion']):0;if(!$d['idPromocion']&&!$nuevas)$e['galeria']='Carga al menos una imagen para la promoción.';if($existentes+count($nuevas)>5)$e['galeria']='Una promoción admite máximo cinco imágenes.';if($e)$this->json(['status'=>'error','message'=>'Revisa los campos marcados.','errors'=>$e],422);$db=Conexion::conectar();$rutas=[];try{$db->beginTransaction();$id=ModeloPromociones::guardar($db,$d);$orden=$existentes+1;foreach($nuevas as$file){$a=$this->subir($file);$rutas[]=$a['ruta'];ModeloPromociones::agregarArchivo($db,$id,$a,$orden++);}$db->commit();$this->json(['status'=>'success','message'=>$d['idPromocion']?'Promoción actualizada correctamente.':'Promoción registrada correctamente.','data'=>['idPromocion'=>$id]],$d['idPromocion']?200:201);}catch(PDOException $x){if($db->inTransaction())$db->rollBack();$this->limpiar($rutas);$this->json(['status'=>'error','message'=>'No fue posible guardar la promoción.'],500);}catch(RuntimeException $x){if($db->inTransaction())$db->rollBack();$this->limpiar($rutas);$this->json(['status'=>'error','message'=>$x->getMessage()],422);}}
 public function cambiarEstado():void{$this->metodo('POST');$in=$this->entrada();$this->csrf($in);$id=filter_var($in['idPromocion']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$activo=filter_var($in['activo']??null,FILTER_VALIDATE_BOOLEAN,FILTER_NULL_ON_FAILURE);if(!$id||$activo===null)$this->json(['status'=>'error','message'=>'Datos no válidos.'],422);if(!ModeloPromociones::cambiarEstado((int)$id,$activo))$this->json(['status'=>'error','message'=>'La promoción no existe o ya tiene ese estado.'],404);$this->json(['status'=>'success','message'=>$activo?'Promoción activada.':'Promoción desactivada.']);}
 private function normalizar(array $i):array{$t=fn($k,$m)=>mb_substr(trim((string)($i[$k]??'')),0,$m);$id=filter_var($i['idPromocion']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);return['idPromocion'=>$id?:null,'idAfiliado'=>(int)($i['idAfiliado']??0),'titulo'=>$t('titulo',180),'descripcion'=>$t('descripcion',5000),'restricciones'=>$t('restricciones',5000),'inicio'=>str_replace('T',' ',$t('inicio_vigencia',19)),'fin'=>str_replace('T',' ',$t('fin_vigencia',19))];}
 private function validar(array $d):array{$e=[];if(!ModeloPromociones::afiliadoActivoExiste($d['idAfiliado']))$e['idAfiliado']='Selecciona un afiliado activo.';if($d['titulo']==='')$e['titulo']='El título es obligatorio.';if($d['descripcion']==='')$e['descripcion']='La descripción es obligatoria.';$i=strtotime($d['inicio']);$f=strtotime($d['fin']);if(!$i)$e['inicio_vigencia']='Captura una fecha de inicio válida.';if(!$f)$e['fin_vigencia']='Captura una fecha de fin válida.';if($i&&$f&&$f<$i)$e['fin_vigencia']='La fecha final no puede ser menor que la inicial.';return$e;}
 private function archivosEntrada(?array $g):array{if(!$g||!is_array($g['name']))return[];$a=[];foreach($g['name']as$i=>$n)if($n!==''){$x=[];foreach(['name','tmp_name','error','size']as$k)$x[$k]=$g[$k][$i];$a[]=$x;}return$a;}
 private function subir(array $f):array{if(($f['error']??0)!==UPLOAD_ERR_OK)throw new RuntimeException('No fue posible cargar una imagen.');if(($f['size']??0)>2097152)throw new RuntimeException('Cada imagen puede pesar máximo 2 MB.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime]??null;if(!$ext||!($dim=getimagesize($f['tmp_name'])))throw new RuntimeException('Solo se permiten imágenes JPG, PNG o WEBP válidas.');$rel='promociones/'.gmdate('Y/m').'/'.bin2hex(random_bytes(16)).'.'.$ext;$ruta=UPLOADS_PATH.$rel;$dir=dirname($ruta);if(!is_dir($dir)&&!mkdir($dir,0755,true)&&!is_dir($dir))throw new RuntimeException('No fue posible preparar el almacenamiento.');if(!move_uploaded_file($f['tmp_name'],$ruta))throw new RuntimeException('No fue posible guardar la imagen.');return['nombre'=>mb_substr(basename($f['name']),0,255),'key'=>$rel,'url'=>base_url('uploads/'.$rel),'mime'=>$mime,'peso'=>(int)$f['size'],'ancho'=>(int)$dim[0],'alto'=>(int)$dim[1],'hash'=>hash_file('sha256',$ruta),'alt'=>'Imagen de promoción','ruta'=>$ruta];}
 private function idGet(string $n):int{$id=filter_input(INPUT_GET,$n,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if(!$id)$this->json(['status'=>'error','message'=>'Identificador inválido.'],422);return(int)$id;}
 private function entrada():array{$d=json_decode((string)file_get_contents('php://input'),true);if(!is_array($d))$this->json(['status'=>'error','message'=>'Solicitud inválida.'],400);return$d;}
 private function csrf(array $in):void{if(!validarTokenCSRF((string)($_SERVER['HTTP_X_CSRF_TOKEN']??($in['csrf_token']??''))))$this->json(['status'=>'error','message'=>'La sesión del formulario expiró. Recarga la página.'],419);}
 private function metodo(string $m):void{if(($_SERVER['REQUEST_METHOD']??'GET')!==$m)$this->json(['status'=>'error','message'=>'Método no permitido.'],405);}
 private function limpiar(array $r):void{foreach($r as$x)if(is_file($x))@unlink($x);}
 private function json(array $d,int $s=200):never{http_response_code($s);header('Content-Type: application/json; charset=utf-8');echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
}
