<?php
declare(strict_types=1);

final class ControladorSucursales
{
    private function autorizar(): void { if(!(tieneRol('ADMIN_GENERAL')||tieneRol('AFILIADO'))||!tienePermiso('sucursales.gestionar'))$this->json(['status'=>'error','message'=>'No tienes permiso para administrar sucursales.'],403); }
    private function alcance(): ?array { $u=obtenerUsuarioSesion();return $u['rol']==='AFILIADO'?array_values(array_unique(array_map('intval',(array)($u['afiliados']??[])))):null; }
    private function autorizarSucursal(int $id): void { $a=$this->alcance();if($a!==null&&!ModeloSucursalesAdmin::perteneceAAlcance($id,$a))$this->json(['status'=>'error','message'=>'La sucursal no existe o no pertenece a tu empresa.'],404); }
    public function index(): array { $this->autorizar();$f=['q'=>mb_substr(trim((string)($_GET['q']??'')),0,100),'afiliado'=>max(0,(int)($_GET['afiliado']??0)),'estado'=>in_array((string)($_GET['estado']??''),['0','1'],true)?(string)$_GET['estado']:''];$a=$this->alcance();return ['filtros'=>$f,'listado'=>ModeloSucursalesAdmin::listar($f,$a),'estadisticas'=>ModeloSucursalesAdmin::resumen($a),'afiliados'=>ModeloSucursalesAdmin::afiliados($a),'esAdminGeneral'=>tieneRol('ADMIN_GENERAL'),'estados'=>ModeloSucursalesAdmin::estados(),'googleMapsKey'=>(string)(getenv('GOOGLE_MAPS_API_KEY')?:'')]; }
    public function obtener(): never { $this->autorizar();$this->metodo('GET');$id=$this->idGet('id');$this->autorizarSucursal($id);$d=ModeloSucursalesAdmin::obtener($id);if(!$d)$this->json(['status'=>'error','message'=>'La sucursal no existe.'],404);$this->json(['status'=>'success','data'=>$d]); }
    public function guardar(): never
    {
        $this->autorizar();$this->metodo('POST');$in=$_POST?:$this->entrada();$this->csrf($in);$id=empty($in['idSucursal'])?null:filter_var($in['idSucursal'],FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$existente=$id?ModeloSucursalesAdmin::obtener((int)$id):null;
        if($id&&!$existente)$this->json(['status'=>'error','message'=>'La sucursal no existe.'],404);if($id)$this->autorizarSucursal((int)$id);$alcance=$this->alcance();
        $d=['id'=>$id?:null,'idAfiliado'=>(int)($in['idAfiliado']??($existente['idAfiliado']??0)),'idLocalidad'=>(int)($in['idLocalidad']??($existente['idLocalidad']??0)),'nombre'=>mb_substr(trim((string)($in['nombre']??'')),0,150),'es_matriz'=>array_key_exists('es_matriz',$in)?((string)$in['es_matriz']==='1'?1:0):(int)($existente['es_matriz']??0),'calle'=>mb_substr(trim((string)($in['calle']??'')),0,160),'numero_exterior'=>mb_substr(trim((string)($in['numero_exterior']??'')),0,20),'numero_interior'=>mb_substr(trim((string)($in['numero_interior']??'')),0,20),'colonia'=>mb_substr(trim((string)($in['colonia']??'')),0,130),'codigo_postal'=>trim((string)($in['codigo_postal']??'')),'referencias'=>mb_substr(trim((string)($in['referencias']??'')),0,500),'latitud'=>trim((string)($in['latitud']??'')),'longitud'=>trim((string)($in['longitud']??'')),'google_place_id'=>mb_substr(trim((string)($in['google_place_id']??'')),0,255),'telefono'=>mb_substr(trim((string)($in['telefono']??'')),0,50),'whatsapp'=>mb_substr(trim((string)($in['whatsapp']??'')),0,50),'extension'=>mb_substr(trim((string)($in['extension_telefono']??($existente['extension_telefono']??''))),0,10),'etiqueta'=>mb_substr(trim((string)($in['etiqueta']??($existente['etiqueta']??''))),0,50),'etiqueta_whatsapp'=>mb_substr(trim((string)($in['etiqueta_whatsapp']??($existente['etiqueta_whatsapp']??''))),0,50)];
        $d=['id'=>$id?:null,'idAfiliado'=>(int)($in['idAfiliado']??($existente['idAfiliado']??0)),'idLocalidad'=>(int)($in['idLocalidad']??($existente['idLocalidad']??0)),'nombre'=>mb_substr(trim((string)($in['nombre']??'')),0,150),'es_matriz'=>array_key_exists('es_matriz',$in)?((string)$in['es_matriz']==='1'?1:0):(int)($existente['es_matriz']??0),'calle'=>mb_substr(trim((string)($in['calle']??'')),0,160),'numero_exterior'=>mb_substr(trim((string)($in['numero_exterior']??'')),0,20),'numero_interior'=>mb_substr(trim((string)($in['numero_interior']??'')),0,20),'colonia'=>mb_substr(trim((string)($in['colonia']??'')),0,130),'codigo_postal'=>trim((string)($in['codigo_postal']??'')),'referencias'=>mb_substr(trim((string)($in['referencias']??'')),0,500),'latitud'=>trim((string)($in['latitud']??'')),'longitud'=>trim((string)($in['longitud']??'')),'google_place_id'=>mb_substr(trim((string)($in['google_place_id']??'')),0,255),'telefono'=>mb_substr(trim((string)($in['telefono']??'')),0,50),'whatsapp'=>mb_substr(trim((string)($in['whatsapp']??'')),0,50),'extension'=>mb_substr(trim((string)($in['extension_telefono']??($existente['extension_telefono']??''))),0,10),'etiqueta'=>mb_substr(trim((string)($in['etiqueta']??($existente['etiqueta']??''))),0,50),'etiqueta_whatsapp'=>mb_substr(trim((string)($in['etiqueta_whatsapp']??($existente['etiqueta_whatsapp']??''))),0,50)];if($alcance!==null&&!in_array($d['idAfiliado'],$alcance,true))$this->json(['status'=>'error','message'=>'Solo puedes administrar sucursales de tu empresa.'],403);
        $errors=[];if(!ModeloSucursalesAdmin::afiliadoUsable($d['idAfiliado'],$d['id']))$errors['idAfiliado']='Selecciona un afiliado activo.';if(!ModeloSucursalesAdmin::localidadExiste($d['idLocalidad']))$errors['idLocalidad']='Selecciona una ciudad activa.';if($d['calle']==='')$errors['calle']='El domicilio es obligatorio.';if($d['telefono']==='')$errors['telefono']='El teléfono es obligatorio.';if(strlen(preg_replace('/\D+/','',$d['telefono'])??'')<7||strlen(preg_replace('/\D+/','',$d['telefono'])??'')>16)$errors['telefono']='Captura un teléfono válido de 7 a 16 dígitos.';if($d['whatsapp']!==''&&(strlen(preg_replace('/\D+/','',$d['whatsapp'])??'')<7||strlen(preg_replace('/\D+/','',$d['whatsapp'])??'')>16))$errors['whatsapp']='Captura un WhatsApp válido de 7 a 16 dígitos.';if($d['extension']!==''&&!preg_match('/^\d+$/',$d['extension']))$errors['extension_telefono']='La extensión debe contener solo dígitos.';if($d['codigo_postal']!==''&&!preg_match('/^\d{5}$/',$d['codigo_postal']))$errors['codigo_postal']='El código postal debe tener cinco dígitos.';
        foreach(['latitud'=>[-90,90],'longitud'=>[-180,180]] as $key=>$rango)if(!is_numeric($d[$key])||(float)$d[$key]<$rango[0]||(float)$d[$key]>$rango[1])$errors['google_place_id']='Selecciona la ubicación de las sugerencias de Google Maps.';
        if($d['google_place_id']==='')$errors['google_place_id']='Selecciona la ubicación de las sugerencias de Google Maps.';if($errors)$this->json(['status'=>'error','message'=>'Revisa los campos marcados.','errors'=>$errors],422);
        $db=Conexion::conectar();try{$db->beginTransaction();$id=ModeloSucursalesAdmin::guardar($db,$d);$db->commit();}catch(Throwable $e){if($db->inTransaction())$db->rollBack();registrarLog('Error al guardar sucursal: '.$e->getMessage(),'ERROR');$this->json(['status'=>'error','message'=>'No fue posible guardar la sucursal. Verifica que sus datos no estén duplicados.'],500);}
        $this->json(['status'=>'success','message'=>$d['id']?'Sucursal actualizada correctamente.':'Sucursal registrada correctamente.','data'=>['idSucursal'=>$id]],$d['id']?200:201);
    }
    public function cambiarEstado(): never { $this->autorizar();$this->metodo('POST');$in=$this->entrada();$this->csrf($in);$id=filter_var($in['idSucursal']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$activo=filter_var($in['activo']??null,FILTER_VALIDATE_BOOLEAN,FILTER_NULL_ON_FAILURE);if(!$id||$activo===null)$this->json(['status'=>'error','message'=>'Datos no válidos.'],422);$this->autorizarSucursal((int)$id);if(!ModeloSucursalesAdmin::cambiarEstado((int)$id,$activo))$this->json(['status'=>'error','message'=>'La sucursal no existe o ya tiene ese estado.'],404);$this->json(['status'=>'success','message'=>$activo?'Sucursal activada.':'Sucursal desactivada.']); }
    private function idGet(string $n):int{$id=filter_input(INPUT_GET,$n,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if(!$id)$this->json(['status'=>'error','message'=>'Identificador inválido.'],422);return(int)$id;}
    private function entrada():array{$x=json_decode((string)file_get_contents('php://input'),true);if(!is_array($x))$this->json(['status'=>'error','message'=>'Solicitud inválida.'],400);return$x;}
    private function csrf(array $x):void{if(!validarTokenCSRF((string)($_SERVER['HTTP_X_CSRF_TOKEN']??($x['csrf_token']??''))))$this->json(['status'=>'error','message'=>'La sesión del formulario expiró. Recarga la página.'],419);}
    private function metodo(string $m):void{if(($_SERVER['REQUEST_METHOD']??'GET')!==$m)$this->json(['status'=>'error','message'=>'Método no permitido.'],405);}
    private function json(array $x,int $status=200):never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');echo json_encode($x,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
}
